### ISSUE TITLE
some 

### ISSUE THREAD

**Issue by LEEGILJUN** [yaojieliu/CVPR2019-DeepTreeLearningForZeroShotFaceAntispoofing#17]
![스크린샷 2020-07-13 오후 2 44 11](https://user-images.githubusercontent.com/23168829/87274764-7ff67780-c517-11ea-8a84-bdc041de34c6.png)

Hi
how to run this script??
when I working the train.py
it some make error...

$ python3 train.py
2020-07-13 14:39:57.524805: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-07-13 14:39:57.577527: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1561] Found device 0 with properties: 
pciBusID: 0000:8a:00.0 name: Tesla V100-SXM2-16GB computeCapability: 7.0
coreClock: 1.53GHz coreCount: 80 deviceMemorySize: 15.78GiB deviceMemoryBandwidth: 836.37GiB/s
2020-07-13 14:39:57.577764: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-07-13 14:39:57.579376: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
2020-07-13 14:39:57.580883: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10
2020-07-13 14:39:57.581165: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10
2020-07-13 14:39:57.583019: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10
2020-07-13 14:39:57.583986: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10
2020-07-13 14:39:57.587860: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-07-13 14:39:57.590829: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1703] Adding visible gpu devices: 0
Traceback (most recent call last):
  File "train.py", line 54, in <module>
    main()
  File "train.py", line 38, in main
    config = Config()
  File "/home/intunit/LGJ/ZSFA/model/config.py", line 59, in __init__
    tf.config.experimental.set_memory_growth(gpus[self.GPU_USAGE], True)
IndexError: list index out of range

**Comment by rathodx** [comment]
Make GPU_USAGE = 1 to GPU_USAGE = 0
