### ISSUE TITLE
Something wrong in "tf.reshape" 

### ISSUE THREAD

**Issue by Sally-fyk** [yaojieliu/CVPR2019-DeepTreeLearningForZeroShotFaceAntispoofing#7]
Traceback (most recent call last):
  File "/home/littlea/CVPR2019-DeepTreeLearningForZeroShotFaceAntispoofing/train.py", line 48, in <module>
    main()
  File "/home/littlea/CVPR2019-DeepTreeLearningForZeroShotFaceAntispoofing/train.py", line 46, in main
    model.train(dataset_train, None)
  File "/home/littlea/CVPR2019-DeepTreeLearningForZeroShotFaceAntispoofing/model/model.py", line 229, in train
    self.train_one_step(next(it), global_step, True)
  File "/home/littlea/CVPR2019-DeepTreeLearningForZeroShotFaceAntispoofing/model/model.py", line 288, in train_one_step
    depth_map_loss = leaf_l1_loss(dmap_pred, tf.image.resize(dmap, [32, 32]), leaf_node_mask)
  File "/home/littlea/CVPR2019-DeepTreeLearningForZeroShotFaceAntispoofing/model/loss.py", line 50, in leaf_l1_loss
    loss = tf.reduce_mean(tf.reshape(tf.abs(x-y), [xshape[0], -1]), axis=1)
  File "/home/littlea/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 7715, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/home/littlea/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 530, in _apply_op_helper
    raise err
  File "/home/littlea/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 527, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/home/littlea/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1224, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/littlea/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 305, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/littlea/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 246, in constant
    allow_broadcast=True)
  File "/home/littlea/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 284, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "/home/littlea/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/python/framework/tensor_util.py", line 562, in make_tensor_proto
    "supported type." % (type(values), values))
TypeError: Failed to convert object of type <class 'list'> to Tensor. Contents: [Dimension(None), -1]. Consider casting elements to a supported type.

**Comment by Sally-fyk** [comment]
遇到了一个很奇怪的问题……
loss = tf.reduce_mean(tf.reshape(tf.abs(x-y), [xshape[0], -1]), axis=1)
这一步tf.reshape竟然有问题，提示xshape[0]为None。
xshape[0]是不是数据的第一个维度，也就是batch_size呢？可是从制作dataset开始这个维度就一直是None，不知道这个问题该怎么解释呢，谢谢解答~

**Comment by yaojieliu** [comment]
因为dataset.map出来的tensor的是[?, H, W, C]. 你已知batch size的情况下，可以强行用tf.reshape把[?, H, W, C]转换成[N, H, W, C]

**Comment by yaojieliu** [comment]
> 遇到了一个很奇怪的问题……
> loss = tf.reduce_mean(tf.reshape(tf.abs(x-y), [xshape[0], -1]), axis=1)
> 这一步tf.reshape竟然有问题，提示xshape[0]为None。
> xshape[0]是不是数据的第一个维度，也就是batch_size呢？可是从制作dataset开始这个维度就一直是None，不知道这个问题该怎么解释呢，谢谢解答~

因为dataset.map出来的tensor的是[?, H, W, C]. 你已知batch size的情况下，可以强行用tf.reshape把[?, H, W, C]转换成[N, H, W, C]
